name: Test with pytest

on: [pull_request, workflow_call]

jobs:
  tests:
    name: Test with py${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true
          mamba-version: "*"
      - name: Install conda dependencies
        shell: bash -el {0}
        run: |
          mamba install -c conda-forge -c bioconda bcftools pip pytest pytest-cov
      - name: Install pytest and trtools
        shell: bash -el {0}
        run: |
          pip install -e .
      - name: Test with pytest
        shell: bash -el {0}
        run: |
          python -m pytest --cov=. --cov-report term-missing --cov-fail-under 89 --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
