name: Tests

on: [pull_request, workflow_call]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test with py${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.7", os: "ubuntu-latest" }
          - { python: "3.8", os: "ubuntu-latest" }
          - { python: "3.9", os: "ubuntu-latest" }
          - { python: "3.10", os: "ubuntu-latest" }
          - { python: "3.11", os: "ubuntu-latest" }
          # - { python: "3.11", os: "windows-latest" }
          - { python: "3.9", os: "macos-latest" }

    env:
      NOXSESSION: tests
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
      - name: Upgrade pip in virtual environments
        shell: python
        run: |
          import os
          import pip
          with open(os.environ["GITHUB_ENV"], mode="a") as io:
              print(f"VIRTUALENV_PIP={pip.__version__}", file=io)
      - name: Install Poetry
        run: |
          if [ "${{ matrix.python }}" = "3.7" ]; then
            pipx install --python python${{ matrix.python }} poetry
          else
            pipx install --python python${{ matrix.python }} --pip-args=--constraint=.github/workflows/constraints.txt poetry
          fi
          poetry --version
      - name: Install Nox
        run: |
          pipx install --python python${{ matrix.python }} --pip-args=--constraint=.github/workflows/constraints.txt nox
          pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry
          nox --version
      - name: Run Nox
        run: |
          nox --python=${{ matrix.python }}
