name: Test with pytest

on: [pull_request, workflow_call]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true
      - name: Install conda dependencies
        run: conda install -c conda-forge -c bioconda bcftools pip
      - name: Install pytest and trtools
        run: |
          pip install pytest pytest-cov trtools
      - name: Test with pytest
        run: |
          bcftools --help
          python -m pytest --cov=. --cov-report term-missing --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
